export const FETCH_BLOGPOSTS_LAST = 'FETCH_BLOGPOSTS_LAST'
export const FETCH_BLOGPOSTS_LAST_FULFILLED  = 'FETCH_BLOGPOSTS_LAST_FULFILLED'
export const FETCH_BLOGPOSTS_LAST_REJECTED = 'FETCH_BLOGPOSTS_LAST_REJECTED'
