export const FETCH_BLOGPOST_LAST = 'FETCH_BLOGPOST_LAST'
export const FETCH_BLOGPOST_LAST_FULFILLED  = 'FETCH_BLOGPOST_LAST_FULFILLED'
export const FETCH_BLOGPOST_LAST_REJECTED = 'FETCH_BLOGPOST_LAST_REJECTED'
